version: '2'
services:
    affexserver-app:
        image: affexserver
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://affexserver-mysql:3306/affexserver?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    affexserver-mysql:
        extends:
            file: mysql.yml
            service: affexserver-mysql
